# NumPy - Numerical Python
- The fundamental package for scientific computing with Python
- https://numpy.org

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
arr.dtype

dtype('int64')

In [9]:
np.array([1, 2, 3.0, 4]).dtype

dtype('float64')

## Matrix vs Vectors

In [10]:
vec = np.array([1, 2, 3])

In [12]:
vec.ndim

1

In [13]:
vec.shape

(3,)

In [20]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [21]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
mat.ndim

2

In [23]:
mat.shape

(4, 3)

Calculations

In [25]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
mat + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
mat + mat

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [27]:
mat*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [28]:
mat + vec

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [29]:
mat, vec

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([1, 2, 3]))

In [30]:
mat*vec

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27],
       [10, 22, 36]])

Useful creations

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones(4)

array([1., 1., 1., 1.])

In [34]:
np.random.random(5)

array([0.8187706 , 0.0924842 , 0.35748529, 0.06594992, 0.30960718])

In [36]:
np.random.normal(5)

4.4290839309502665

In [39]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])