In [1]:
import numpy as np

In [2]:
arr = np.arange(12)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr[5]

5

In [5]:
arr[3:6]

array([3, 4, 5])

In [6]:
arr[:-3]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr[-1]

11

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
arr[5:8] = 12

In [10]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11])

In [11]:
arr_slice = arr[1:4]

In [12]:
arr_slice

array([1, 2, 3])

In [13]:
arr_slice[:] = 0

In [14]:
arr_slice

array([0, 0, 0])

In [15]:
arr

array([ 0,  0,  0,  0,  4, 12, 12, 12,  8,  9, 10, 11])

In [16]:
arr_slice[0] = -1

In [17]:
arr

array([ 0, -1,  0,  0,  4, 12, 12, 12,  8,  9, 10, 11])

In [18]:
arr = np.arange(12)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
arr_copy = arr[3:6].copy()

In [21]:
arr_copy

array([3, 4, 5])

In [22]:
arr_copy[:] = -1

In [23]:
arr_copy

array([-1, -1, -1])

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Matrix

In [25]:
mat = np.arange(12).reshape(3, 4)

In [26]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
mat[0, 2]

2

In [28]:
mat[0][2]

2

In [30]:
mat[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [31]:
mat_slice = mat[0:2, 1:3]

In [32]:
mat_slice[:] = -1

In [33]:
mat_slice

array([[-1, -1],
       [-1, -1]])

In [34]:
mat

array([[ 0, -1, -1,  3],
       [ 4, -1, -1,  7],
       [ 8,  9, 10, 11]])

In [35]:
mat_copy = mat[0:2, 1:3].copy()

In [36]:
mat_copy

array([[-1, -1],
       [-1, -1]])

In [37]:
mat_copy[:] = -10

In [38]:
mat_copy

array([[-10, -10],
       [-10, -10]])

In [39]:
mat

array([[ 0, -1, -1,  3],
       [ 4, -1, -1,  7],
       [ 8,  9, 10, 11]])

In [40]:
mat_copy = -7

In [41]:
mat_copy

-7

In [42]:
type(mat_copy)

int