In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("ticker-fb.csv", index_col=0, parse_dates=True)

In [3]:
data.head()

High         Low        Open       Close    Volume  \
Date                                                                   
2018-01-02  181.580002  177.550003  177.679993  181.419998  18151900   
2018-01-03  184.779999  181.330002  181.880005  184.669998  16886600   
2018-01-04  186.210007  184.100006  184.899994  184.330002  13880900   
2018-01-05  186.899994  184.929993  185.589996  186.850006  13574500   
2018-01-08  188.899994  186.330002  187.199997  188.279999  17994700   

             Adj Close  
Date                    
2018-01-02  181.419998  
2018-01-03  184.669998  
2018-01-04  184.330002  
2018-01-05  186.850006  
2018-01-08  188.279999

In [5]:
type(data.values)

numpy.ndarray

In [6]:
arr = data.values

In [7]:
arr.shape

(756, 6)

In [8]:
len(data)

756

In [9]:
arr.ndim

2

In [10]:
arr.dtype

dtype('float64')

In [12]:
col = data['Close'].values

In [14]:
col.shape

(756,)

In [15]:
col.ndim

1

In [16]:
col.dtype

dtype('float64')

In [17]:
vol = data['Volume'].values

In [18]:
vol.dtype

dtype('int64')

In [19]:
data.dtypes

High         float64
Low          float64
Open         float64
Close        float64
Volume         int64
Adj Close    float64
dtype: object

## Reshape

In [20]:
arr = data['Close'].iloc[-12:].values

In [21]:
arr

array([275.54998779, 275.67001343, 274.48001099, 276.3999939 ,
       272.79000854, 267.08999634, 268.10998535, 267.3999939 ,
       277.        , 276.77999878, 271.86999512, 273.16000366])

In [22]:
arr.shape

(12,)

In [23]:
arr.ndim

1

In [24]:
arr.dtype

dtype('float64')

In [25]:
arr.reshape(3, 4)

array([[275.54998779, 275.67001343, 274.48001099, 276.3999939 ],
       [272.79000854, 267.08999634, 268.10998535, 267.3999939 ],
       [277.        , 276.77999878, 271.86999512, 273.16000366]])

In [26]:
arr.reshape(4, 3)

array([[275.54998779, 275.67001343, 274.48001099],
       [276.3999939 , 272.79000854, 267.08999634],
       [268.10998535, 267.3999939 , 277.        ],
       [276.77999878, 271.86999512, 273.16000366]])

In [28]:
arr.reshape(12, 1)

array([[275.54998779],
       [275.67001343],
       [274.48001099],
       [276.3999939 ],
       [272.79000854],
       [267.08999634],
       [268.10998535],
       [267.3999939 ],
       [277.        ],
       [276.77999878],
       [271.86999512],
       [273.16000366]])

In [29]:
arr.reshape(len(arr), 1)

array([[275.54998779],
       [275.67001343],
       [274.48001099],
       [276.3999939 ],
       [272.79000854],
       [267.08999634],
       [268.10998535],
       [267.3999939 ],
       [277.        ],
       [276.77999878],
       [271.86999512],
       [273.16000366]])

In [30]:
arr.reshape(-1, 1)

array([[275.54998779],
       [275.67001343],
       [274.48001099],
       [276.3999939 ],
       [272.79000854],
       [267.08999634],
       [268.10998535],
       [267.3999939 ],
       [277.        ],
       [276.77999878],
       [271.86999512],
       [273.16000366]])

## Multiplication

In [31]:
data.head()

High         Low        Open       Close    Volume  \
Date                                                                   
2018-01-02  181.580002  177.550003  177.679993  181.419998  18151900   
2018-01-03  184.779999  181.330002  181.880005  184.669998  16886600   
2018-01-04  186.210007  184.100006  184.899994  184.330002  13880900   
2018-01-05  186.899994  184.929993  185.589996  186.850006  13574500   
2018-01-08  188.899994  186.330002  187.199997  188.279999  17994700   

             Adj Close  
Date                    
2018-01-02  181.419998  
2018-01-03  184.669998  
2018-01-04  184.330002  
2018-01-05  186.850006  
2018-01-08  188.279999

In [35]:
data*np.array([0.2, 0.3, 0.4, 0.1, 0, 0])*10000

High            Low          Open          Close  Volume  \
Date                                                                            
2018-01-02  363160.003662  532650.009155  7.107200e+05  181419.998169     0.0   
2018-01-03  369559.997559  543990.005493  7.275200e+05  184669.998169     0.0   
2018-01-04  372420.013428  552300.018311  7.396000e+05  184330.001831     0.0   
2018-01-05  373799.987793  554789.978027  7.423600e+05  186850.006104     0.0   
2018-01-08  377799.987793  558990.005493  7.488000e+05  188279.998779     0.0   
...                   ...            ...           ...            ...     ...   
2020-12-24  540799.987793  798600.036621  1.075520e+06  267399.993896     0.0   
2020-12-28  554599.975586  796980.010986  1.074960e+06  277000.000000     0.0   
2020-12-29  561020.019531  828839.996338  1.107800e+06  276779.998779     0.0   
2020-12-30  556159.973145  815129.974365  1.111800e+06  271869.995117     0.0   
2020-12-31  554179.992676  809429.992676  1.088000e+06  273160.003662     0.0   

            Adj Close  
Date                   
2018-01-02        0.0  
2018-01-03        0.0  
2018-01-04        0.0  
2018-01-05        0.0  
2018-01-08        0.0  
...               ...  
2020-12-24        0.0  
2020-12-28        0.0  
2020-12-29        0.0  
2020-12-30        0.0  
2020-12-31        0.0  

[756 rows x 6 columns]