In [1]:
import numpy as np

In [2]:
arr1 = np.random.random(5)

In [3]:
arr2 = np.random.random(5)

In [4]:
arr1, arr2

(array([0.6583339 , 0.16893551, 0.94246724, 0.96151883, 0.69387343]),
 array([0.52817301, 0.6701988 , 0.67436219, 0.58795987, 0.81530684]))

In [5]:
arr1 * arr2

array([0.3477142 , 0.11322037, 0.63556427, 0.56533449, 0.56571975])

In [6]:
arr1[0]*arr2[0]

0.3477141953005951

In [7]:
np.dot(arr1, arr2)

2.2275530795558196

In [9]:
(arr1 * arr2).sum()

2.22755307955582

In [10]:
mat = np.random.random(9).reshape(3, 3)

In [11]:
mat

array([[8.10485623e-01, 7.25318512e-01, 8.49880544e-01],
       [8.85124800e-02, 3.75811026e-01, 8.68776816e-01],
       [2.77306365e-01, 3.20090039e-04, 8.48723265e-01]])

In [13]:
arr = np.random.random(3)

In [14]:
arr

array([0.69052776, 0.41876861, 0.43505765])

In [15]:
np.dot(mat, arr)

array([1.23315047, 0.59646618, 0.56086533])

In [19]:
np.dot(mat[2], arr)

0.5608653316981093

In [20]:
np.dot(arr, np.dot(mat, arr))

1.345314691176185

In [21]:
mat = np.random.random(6).reshape(2, 3)

In [22]:
mat

array([[0.00418682, 0.27079144, 0.10260219],
       [0.19725671, 0.58503841, 0.00742467]])

In [23]:
np.dot(mat, arr)

array([0.16092793, 0.38443711])

In [24]:
mat.T

array([[0.00418682, 0.19725671],
       [0.27079144, 0.58503841],
       [0.10260219, 0.00742467]])

In [25]:
mat.transpose()

array([[0.00418682, 0.19725671],
       [0.27079144, 0.58503841],
       [0.10260219, 0.00742467]])

In [26]:
np.dot(mat.T, arr)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)